# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Soreline
tagline:             'Pevska skupina'
description:         'Smo glasbena skupina devetih deklet iz Trebnjega in bližnje okolice. Na našem pestrem glasbenem meniju najdete slovenske, tuje, ljudske, cerkvene skladbe z inštrumenti ali brez. Slišite nas lahko na poročnih in kulturnih slovesnostih, zabavah...:)'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Soreline
  url:               https://sl-si.facebook.com/Soreline-329183587170502/
  email:             soreline09@gmail.com

# Custom vars
version:             0.0.1
