# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Soreline
tagline:             'Pevska skupina'
description:         'Spletna stran ženske pevske skupine Soreline.\nMade by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://soreline.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://sl-si.facebook.com/Soreline-329183587170502/
  email:             vse.zivo3@gmail.com

# Custom vars
version:             1.0.0
